---
deployment:
  tasks:
    - export APPROOT="$(pwd)"
    - export DEPLOYPATH="$HOME/public_html"
    - cd "$APPROOT"
    - npm ci
    - npm run build
    - /bin/rm -rf "$DEPLOYPATH/assets" "$DEPLOYPATH/index.html"
    - /bin/cp -R "$APPROOT/dist/"* "$DEPLOYPATH/"
    - cd "$APPROOT/backend"
    - npm ci
    - npx tsc
    - npx tsc-alias
    - mkdir -p "$APPROOT/backend/uploads"
    - mkdir -p "$APPROOT/backend/tmp" && touch "$APPROOT/backend/tmp/restart.txt"
    - if [ ! -f "$DEPLOYPATH/.htaccess" ]; then cp "$APPROOT/public/.htaccess" "$DEPLOYPATH/.htaccess"; fi
    
