---
deployment:
  tasks:
    - export APPROOT="$(pwd)"
    - export DEPLOYPATH="/home/idealstayco/public_html"
    - /bin/echo "== Deploy start =="
    - /bin/ls -la "$APPROOT"
    - /bin/ls -la "$APPROOT/dist" || true
    - /bin/mkdir -p "$DEPLOYPATH"
    - /bin/rm -rf "$DEPLOYPATH/assets" "$DEPLOYPATH/index.html" || true
    - /bin/cp -R "$APPROOT/dist/"* "$DEPLOYPATH/" || true
    - cd "$APPROOT/backend"
    - /bin/mkdir -p "$APPROOT/backend/uploads"
    - /bin/mkdir -p "$APPROOT/backend/tmp" && touch "$APPROOT/backend/tmp/restart.txt"
    - /bin/echo "== Deploy end =="
    
